export const LOG_IN = 'LOG_IN';

export const LOG_IN_BEGIN = 'LOG_IN_BEGIN';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const ADD_USER_DETAILS_BEGIN = 'ADD_USER_DETAILS_BEGIN';
export const ADD_USER_DETAILS_SUCCESS = 'ADD_USER_DETAILS_SUCCESS';
export const ADD_USER_DETAILS_FAILURE = 'ADD_USER_DETAILS_FAILURE';
